package com.qtt.sms.model;

import java.util.Date;

public class Agent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.account
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.accid
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String accid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.password
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.name
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.key_value
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String keyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.app_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.port
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.given_balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer givenBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.status
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.email
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.mobile
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.reg_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date regAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.login_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date loginAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.update_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date updateAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.id
     *
     * @return the value of agent.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.id
     *
     * @param id the value for agent.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.account
     *
     * @return the value of agent.account
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.account
     *
     * @param account the value for agent.account
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.accid
     *
     * @return the value of agent.accid
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getAccid() {
        return accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.accid
     *
     * @param accid the value for agent.accid
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setAccid(String accid) {
        this.accid = accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.password
     *
     * @return the value of agent.password
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.password
     *
     * @param password the value for agent.password
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.name
     *
     * @return the value of agent.name
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.name
     *
     * @param name the value for agent.name
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.key_value
     *
     * @return the value of agent.key_value
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.key_value
     *
     * @param keyValue the value for agent.key_value
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.app_id
     *
     * @return the value of agent.app_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.app_id
     *
     * @param appId the value for agent.app_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.port
     *
     * @return the value of agent.port
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.port
     *
     * @param port the value for agent.port
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.balance
     *
     * @return the value of agent.balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.balance
     *
     * @param balance the value for agent.balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.given_balance
     *
     * @return the value of agent.given_balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getGivenBalance() {
        return givenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.given_balance
     *
     * @param givenBalance the value for agent.given_balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setGivenBalance(Integer givenBalance) {
        this.givenBalance = givenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.status
     *
     * @return the value of agent.status
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.status
     *
     * @param status the value for agent.status
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.email
     *
     * @return the value of agent.email
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.email
     *
     * @param email the value for agent.email
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.mobile
     *
     * @return the value of agent.mobile
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.mobile
     *
     * @param mobile the value for agent.mobile
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.reg_at
     *
     * @return the value of agent.reg_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getRegAt() {
        return regAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.reg_at
     *
     * @param regAt the value for agent.reg_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setRegAt(Date regAt) {
        this.regAt = regAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.login_at
     *
     * @return the value of agent.login_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getLoginAt() {
        return loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.login_at
     *
     * @param loginAt the value for agent.login_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setLoginAt(Date loginAt) {
        this.loginAt = loginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.update_at
     *
     * @return the value of agent.update_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.update_at
     *
     * @param updateAt the value for agent.update_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
    
    public String getStatusDesc() {
        String desc = "";
        switch (status) {
        case 0: desc = "正常"; break;
        case 1: desc = "未激活"; break;
        case 2: desc = "锁定"; break;
        default: break;
        }
        return desc;
    }
}