package com.qtt.sms.model;

import java.util.Date;

public class AgentSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_session.session_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_session.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_session.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_session.session_id
     *
     * @return the value of agent_session.session_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_session.session_id
     *
     * @param sessionId the value for agent_session.session_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_session.agent_id
     *
     * @return the value of agent_session.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_session.agent_id
     *
     * @param agentId the value for agent_session.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_session.create_at
     *
     * @return the value of agent_session.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_session.create_at
     *
     * @param createAt the value for agent_session.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}