package com.qtt.sms.model;

import java.util.Date;

public class CounterDaily {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_daily.id
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_daily.agent_id
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_daily.rec_date
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    private Date recDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_daily.success
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    private Integer success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_daily.fail
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    private Integer fail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column counter_daily.create_at
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_daily.id
     *
     * @return the value of counter_daily.id
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_daily.id
     *
     * @param id the value for counter_daily.id
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_daily.agent_id
     *
     * @return the value of counter_daily.agent_id
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_daily.agent_id
     *
     * @param agentId the value for counter_daily.agent_id
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_daily.rec_date
     *
     * @return the value of counter_daily.rec_date
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public Date getRecDate() {
        return recDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_daily.rec_date
     *
     * @param recDate the value for counter_daily.rec_date
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public void setRecDate(Date recDate) {
        this.recDate = recDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_daily.success
     *
     * @return the value of counter_daily.success
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public Integer getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_daily.success
     *
     * @param success the value for counter_daily.success
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public void setSuccess(Integer success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_daily.fail
     *
     * @return the value of counter_daily.fail
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public Integer getFail() {
        return fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_daily.fail
     *
     * @param fail the value for counter_daily.fail
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public void setFail(Integer fail) {
        this.fail = fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column counter_daily.create_at
     *
     * @return the value of counter_daily.create_at
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column counter_daily.create_at
     *
     * @param createAt the value for counter_daily.create_at
     *
     * @mbggenerated Mon Dec 28 18:20:53 CST 2015
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}