package com.qtt.sms.model;

import java.util.Date;

import com.qtt.sms.util.CodeUtil;

public class FailRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.agent_id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.phones
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private String phones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.content
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.resp_code
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private String respCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.send_at
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private Date sendAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.count
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.template_id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail_record.type
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.id
     *
     * @return the value of fail_record.id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.id
     *
     * @param id the value for fail_record.id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.agent_id
     *
     * @return the value of fail_record.agent_id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.agent_id
     *
     * @param agentId the value for fail_record.agent_id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.phones
     *
     * @return the value of fail_record.phones
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public String getPhones() {
        return phones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.phones
     *
     * @param phones the value for fail_record.phones
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setPhones(String phones) {
        this.phones = phones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.content
     *
     * @return the value of fail_record.content
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.content
     *
     * @param content the value for fail_record.content
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.resp_code
     *
     * @return the value of fail_record.resp_code
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.resp_code
     *
     * @param respCode the value for fail_record.resp_code
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.send_at
     *
     * @return the value of fail_record.send_at
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public Date getSendAt() {
        return sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.send_at
     *
     * @param sendAt the value for fail_record.send_at
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setSendAt(Date sendAt) {
        this.sendAt = sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.count
     *
     * @return the value of fail_record.count
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.count
     *
     * @param count the value for fail_record.count
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.template_id
     *
     * @return the value of fail_record.template_id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.template_id
     *
     * @param templateId the value for fail_record.template_id
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail_record.type
     *
     * @return the value of fail_record.type
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail_record.type
     *
     * @param type the value for fail_record.type
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }
    
    public int getAgentCode() {
        return CodeUtil.getCodeForAgent(this.respCode);
    }
    
    public String getCodeDesc() {
        return CodeUtil.getCodeDesc(this.respCode);
    }
    
    public String getTypeDesc() {
        String result = "";
        switch (this.type) {
        case 1: result = "行业邮件短信"; break;
        case 2: result = "营销邮件短信"; break;
        case 3: result = "行业短信"; break;
        case 4: result = "营销短信"; break;
        default: result = "未知"; break;
        }
        return result;    	
    }
}