package com.qtt.sms.model;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.ip
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date logAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.uri
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.query_
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String query;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_id
     *
     * @return the value of log.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_id
     *
     * @param userId the value for log.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.ip
     *
     * @return the value of log.ip
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.ip
     *
     * @param ip the value for log.ip
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_at
     *
     * @return the value of log.log_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getLogAt() {
        return logAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_at
     *
     * @param logAt the value for log.log_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setLogAt(Date logAt) {
        this.logAt = logAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.uri
     *
     * @return the value of log.uri
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.uri
     *
     * @param uri the value for log.uri
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.query_
     *
     * @return the value of log.query_
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.query_
     *
     * @param query the value for log.query_
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setQuery(String query) {
        this.query = query;
    }
}