package com.qtt.sms.model;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.port
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private String port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.phone
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.send_at
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private Date sendAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.stamp
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private String stamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.sign
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.create_at
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.port
     *
     * @return the value of notice.port
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.port
     *
     * @param port the value for notice.port
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setPort(String port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.phone
     *
     * @return the value of notice.phone
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.phone
     *
     * @param phone the value for notice.phone
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.send_at
     *
     * @return the value of notice.send_at
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public Date getSendAt() {
        return sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.send_at
     *
     * @param sendAt the value for notice.send_at
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setSendAt(Date sendAt) {
        this.sendAt = sendAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.stamp
     *
     * @return the value of notice.stamp
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public String getStamp() {
        return stamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.stamp
     *
     * @param stamp the value for notice.stamp
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setStamp(String stamp) {
        this.stamp = stamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.sign
     *
     * @return the value of notice.sign
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.sign
     *
     * @param sign the value for notice.sign
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.create_at
     *
     * @return the value of notice.create_at
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.create_at
     *
     * @param createAt the value for notice.create_at
     *
     * @mbggenerated Tue Mar 22 10:32:10 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}