package com.qtt.sms.model;

import java.util.Date;

public class Passageway {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.id
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.name
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.cmcc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer cmcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.cucc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer cucc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.ctcc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer ctcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.status
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.create_at
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.create_by
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.update_at
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passageway.update_by
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    private Integer updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.id
     *
     * @return the value of passageway.id
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.id
     *
     * @param id the value for passageway.id
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.name
     *
     * @return the value of passageway.name
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.name
     *
     * @param name the value for passageway.name
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.cmcc
     *
     * @return the value of passageway.cmcc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getCmcc() {
        return cmcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.cmcc
     *
     * @param cmcc the value for passageway.cmcc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setCmcc(Integer cmcc) {
        this.cmcc = cmcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.cucc
     *
     * @return the value of passageway.cucc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getCucc() {
        return cucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.cucc
     *
     * @param cucc the value for passageway.cucc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setCucc(Integer cucc) {
        this.cucc = cucc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.ctcc
     *
     * @return the value of passageway.ctcc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getCtcc() {
        return ctcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.ctcc
     *
     * @param ctcc the value for passageway.ctcc
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setCtcc(Integer ctcc) {
        this.ctcc = ctcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.status
     *
     * @return the value of passageway.status
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.status
     *
     * @param status the value for passageway.status
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.create_at
     *
     * @return the value of passageway.create_at
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.create_at
     *
     * @param createAt the value for passageway.create_at
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.create_by
     *
     * @return the value of passageway.create_by
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.create_by
     *
     * @param createBy the value for passageway.create_by
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.update_at
     *
     * @return the value of passageway.update_at
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.update_at
     *
     * @param updateAt the value for passageway.update_at
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passageway.update_by
     *
     * @return the value of passageway.update_by
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passageway.update_by
     *
     * @param updateBy the value for passageway.update_by
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
}