package com.qtt.sms.model;

import java.util.Date;

public class RechargeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.given_balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer givenBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.intro
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_log.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.id
     *
     * @return the value of recharge_log.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.id
     *
     * @param id the value for recharge_log.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.agent_id
     *
     * @return the value of recharge_log.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.agent_id
     *
     * @param agentId the value for recharge_log.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.balance
     *
     * @return the value of recharge_log.balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.balance
     *
     * @param balance the value for recharge_log.balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.given_balance
     *
     * @return the value of recharge_log.given_balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getGivenBalance() {
        return givenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.given_balance
     *
     * @param givenBalance the value for recharge_log.given_balance
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setGivenBalance(Integer givenBalance) {
        this.givenBalance = givenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.user_id
     *
     * @return the value of recharge_log.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.user_id
     *
     * @param userId the value for recharge_log.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.intro
     *
     * @return the value of recharge_log.intro
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.intro
     *
     * @param intro the value for recharge_log.intro
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_log.create_at
     *
     * @return the value of recharge_log.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_log.create_at
     *
     * @param createAt the value for recharge_log.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}