package com.qtt.sms.model;

import java.util.Date;

public class RecvRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.phones
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String phones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.content
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.smsid
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String smsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.status
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.resp_code
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String respCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recv_record.recv_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date recvAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.id
     *
     * @return the value of recv_record.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.id
     *
     * @param id the value for recv_record.id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.agent_id
     *
     * @return the value of recv_record.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.agent_id
     *
     * @param agentId the value for recv_record.agent_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.phones
     *
     * @return the value of recv_record.phones
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getPhones() {
        return phones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.phones
     *
     * @param phones the value for recv_record.phones
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setPhones(String phones) {
        this.phones = phones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.content
     *
     * @return the value of recv_record.content
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.content
     *
     * @param content the value for recv_record.content
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.smsid
     *
     * @return the value of recv_record.smsid
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getSmsid() {
        return smsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.smsid
     *
     * @param smsid the value for recv_record.smsid
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setSmsid(String smsid) {
        this.smsid = smsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.status
     *
     * @return the value of recv_record.status
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.status
     *
     * @param status the value for recv_record.status
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.resp_code
     *
     * @return the value of recv_record.resp_code
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.resp_code
     *
     * @param respCode the value for recv_record.resp_code
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setRespCode(String respCode) {
        this.respCode = respCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recv_record.recv_at
     *
     * @return the value of recv_record.recv_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getRecvAt() {
        return recvAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recv_record.recv_at
     *
     * @param recvAt the value for recv_record.recv_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setRecvAt(Date recvAt) {
        this.recvAt = recvAt;
    }
}