package com.qtt.sms.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SendRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public SendRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSmsidIsNull() {
            addCriterion("smsid is null");
            return (Criteria) this;
        }

        public Criteria andSmsidIsNotNull() {
            addCriterion("smsid is not null");
            return (Criteria) this;
        }

        public Criteria andSmsidEqualTo(String value) {
            addCriterion("smsid =", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidNotEqualTo(String value) {
            addCriterion("smsid <>", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidGreaterThan(String value) {
            addCriterion("smsid >", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidGreaterThanOrEqualTo(String value) {
            addCriterion("smsid >=", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidLessThan(String value) {
            addCriterion("smsid <", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidLessThanOrEqualTo(String value) {
            addCriterion("smsid <=", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidLike(String value) {
            addCriterion("smsid like", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidNotLike(String value) {
            addCriterion("smsid not like", value, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidIn(List<String> values) {
            addCriterion("smsid in", values, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidNotIn(List<String> values) {
            addCriterion("smsid not in", values, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidBetween(String value1, String value2) {
            addCriterion("smsid between", value1, value2, "smsid");
            return (Criteria) this;
        }

        public Criteria andSmsidNotBetween(String value1, String value2) {
            addCriterion("smsid not between", value1, value2, "smsid");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNull() {
            addCriterion("agent_id is null");
            return (Criteria) this;
        }

        public Criteria andAgentIdIsNotNull() {
            addCriterion("agent_id is not null");
            return (Criteria) this;
        }

        public Criteria andAgentIdEqualTo(Integer value) {
            addCriterion("agent_id =", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotEqualTo(Integer value) {
            addCriterion("agent_id <>", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThan(Integer value) {
            addCriterion("agent_id >", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("agent_id >=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThan(Integer value) {
            addCriterion("agent_id <", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdLessThanOrEqualTo(Integer value) {
            addCriterion("agent_id <=", value, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdIn(List<Integer> values) {
            addCriterion("agent_id in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotIn(List<Integer> values) {
            addCriterion("agent_id not in", values, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdBetween(Integer value1, Integer value2) {
            addCriterion("agent_id between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andAgentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("agent_id not between", value1, value2, "agentId");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIsNull() {
            addCriterion("query_status is null");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIsNotNull() {
            addCriterion("query_status is not null");
            return (Criteria) this;
        }

        public Criteria andQueryStatusEqualTo(Integer value) {
            addCriterion("query_status =", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotEqualTo(Integer value) {
            addCriterion("query_status <>", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusGreaterThan(Integer value) {
            addCriterion("query_status >", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("query_status >=", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusLessThan(Integer value) {
            addCriterion("query_status <", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusLessThanOrEqualTo(Integer value) {
            addCriterion("query_status <=", value, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusIn(List<Integer> values) {
            addCriterion("query_status in", values, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotIn(List<Integer> values) {
            addCriterion("query_status not in", values, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusBetween(Integer value1, Integer value2) {
            addCriterion("query_status between", value1, value2, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andQueryStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("query_status not between", value1, value2, "queryStatus");
            return (Criteria) this;
        }

        public Criteria andPhonesIsNull() {
            addCriterion("phones is null");
            return (Criteria) this;
        }

        public Criteria andPhonesIsNotNull() {
            addCriterion("phones is not null");
            return (Criteria) this;
        }

        public Criteria andPhonesEqualTo(String value) {
            addCriterion("phones =", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesNotEqualTo(String value) {
            addCriterion("phones <>", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesGreaterThan(String value) {
            addCriterion("phones >", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesGreaterThanOrEqualTo(String value) {
            addCriterion("phones >=", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesLessThan(String value) {
            addCriterion("phones <", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesLessThanOrEqualTo(String value) {
            addCriterion("phones <=", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesLike(String value) {
            addCriterion("phones like", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesNotLike(String value) {
            addCriterion("phones not like", value, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesIn(List<String> values) {
            addCriterion("phones in", values, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesNotIn(List<String> values) {
            addCriterion("phones not in", values, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesBetween(String value1, String value2) {
            addCriterion("phones between", value1, value2, "phones");
            return (Criteria) this;
        }

        public Criteria andPhonesNotBetween(String value1, String value2) {
            addCriterion("phones not between", value1, value2, "phones");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andFailCountIsNull() {
            addCriterion("fail_count is null");
            return (Criteria) this;
        }

        public Criteria andFailCountIsNotNull() {
            addCriterion("fail_count is not null");
            return (Criteria) this;
        }

        public Criteria andFailCountEqualTo(Integer value) {
            addCriterion("fail_count =", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotEqualTo(Integer value) {
            addCriterion("fail_count <>", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountGreaterThan(Integer value) {
            addCriterion("fail_count >", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("fail_count >=", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLessThan(Integer value) {
            addCriterion("fail_count <", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountLessThanOrEqualTo(Integer value) {
            addCriterion("fail_count <=", value, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountIn(List<Integer> values) {
            addCriterion("fail_count in", values, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotIn(List<Integer> values) {
            addCriterion("fail_count not in", values, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountBetween(Integer value1, Integer value2) {
            addCriterion("fail_count between", value1, value2, "failCount");
            return (Criteria) this;
        }

        public Criteria andFailCountNotBetween(Integer value1, Integer value2) {
            addCriterion("fail_count not between", value1, value2, "failCount");
            return (Criteria) this;
        }

        public Criteria andRespStatusIsNull() {
            addCriterion("resp_status is null");
            return (Criteria) this;
        }

        public Criteria andRespStatusIsNotNull() {
            addCriterion("resp_status is not null");
            return (Criteria) this;
        }

        public Criteria andRespStatusEqualTo(Integer value) {
            addCriterion("resp_status =", value, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusNotEqualTo(Integer value) {
            addCriterion("resp_status <>", value, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusGreaterThan(Integer value) {
            addCriterion("resp_status >", value, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("resp_status >=", value, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusLessThan(Integer value) {
            addCriterion("resp_status <", value, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusLessThanOrEqualTo(Integer value) {
            addCriterion("resp_status <=", value, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusIn(List<Integer> values) {
            addCriterion("resp_status in", values, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusNotIn(List<Integer> values) {
            addCriterion("resp_status not in", values, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusBetween(Integer value1, Integer value2) {
            addCriterion("resp_status between", value1, value2, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("resp_status not between", value1, value2, "respStatus");
            return (Criteria) this;
        }

        public Criteria andRespMessageIsNull() {
            addCriterion("resp_message is null");
            return (Criteria) this;
        }

        public Criteria andRespMessageIsNotNull() {
            addCriterion("resp_message is not null");
            return (Criteria) this;
        }

        public Criteria andRespMessageEqualTo(String value) {
            addCriterion("resp_message =", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotEqualTo(String value) {
            addCriterion("resp_message <>", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageGreaterThan(String value) {
            addCriterion("resp_message >", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageGreaterThanOrEqualTo(String value) {
            addCriterion("resp_message >=", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageLessThan(String value) {
            addCriterion("resp_message <", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageLessThanOrEqualTo(String value) {
            addCriterion("resp_message <=", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageLike(String value) {
            addCriterion("resp_message like", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotLike(String value) {
            addCriterion("resp_message not like", value, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageIn(List<String> values) {
            addCriterion("resp_message in", values, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotIn(List<String> values) {
            addCriterion("resp_message not in", values, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageBetween(String value1, String value2) {
            addCriterion("resp_message between", value1, value2, "respMessage");
            return (Criteria) this;
        }

        public Criteria andRespMessageNotBetween(String value1, String value2) {
            addCriterion("resp_message not between", value1, value2, "respMessage");
            return (Criteria) this;
        }

        public Criteria andSendAtIsNull() {
            addCriterion("send_at is null");
            return (Criteria) this;
        }

        public Criteria andSendAtIsNotNull() {
            addCriterion("send_at is not null");
            return (Criteria) this;
        }

        public Criteria andSendAtEqualTo(Date value) {
            addCriterion("send_at =", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtNotEqualTo(Date value) {
            addCriterion("send_at <>", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtGreaterThan(Date value) {
            addCriterion("send_at >", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtGreaterThanOrEqualTo(Date value) {
            addCriterion("send_at >=", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtLessThan(Date value) {
            addCriterion("send_at <", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtLessThanOrEqualTo(Date value) {
            addCriterion("send_at <=", value, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtIn(List<Date> values) {
            addCriterion("send_at in", values, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtNotIn(List<Date> values) {
            addCriterion("send_at not in", values, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtBetween(Date value1, Date value2) {
            addCriterion("send_at between", value1, value2, "sendAt");
            return (Criteria) this;
        }

        public Criteria andSendAtNotBetween(Date value1, Date value2) {
            addCriterion("send_at not between", value1, value2, "sendAt");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdIsNull() {
            addCriterion("passageway_id is null");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdIsNotNull() {
            addCriterion("passageway_id is not null");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdEqualTo(Integer value) {
            addCriterion("passageway_id =", value, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdNotEqualTo(Integer value) {
            addCriterion("passageway_id <>", value, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdGreaterThan(Integer value) {
            addCriterion("passageway_id >", value, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("passageway_id >=", value, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdLessThan(Integer value) {
            addCriterion("passageway_id <", value, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdLessThanOrEqualTo(Integer value) {
            addCriterion("passageway_id <=", value, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdIn(List<Integer> values) {
            addCriterion("passageway_id in", values, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdNotIn(List<Integer> values) {
            addCriterion("passageway_id not in", values, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdBetween(Integer value1, Integer value2) {
            addCriterion("passageway_id between", value1, value2, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andPassagewayIdNotBetween(Integer value1, Integer value2) {
            addCriterion("passageway_id not between", value1, value2, "passagewayId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNull() {
            addCriterion("template_id is null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIsNotNull() {
            addCriterion("template_id is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateIdEqualTo(String value) {
            addCriterion("template_id =", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotEqualTo(String value) {
            addCriterion("template_id <>", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThan(String value) {
            addCriterion("template_id >", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdGreaterThanOrEqualTo(String value) {
            addCriterion("template_id >=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThan(String value) {
            addCriterion("template_id <", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLessThanOrEqualTo(String value) {
            addCriterion("template_id <=", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdLike(String value) {
            addCriterion("template_id like", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotLike(String value) {
            addCriterion("template_id not like", value, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdIn(List<String> values) {
            addCriterion("template_id in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotIn(List<String> values) {
            addCriterion("template_id not in", values, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdBetween(String value1, String value2) {
            addCriterion("template_id between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTemplateIdNotBetween(String value1, String value2) {
            addCriterion("template_id not between", value1, value2, "templateId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table send_record
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 28 10:41:33 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table send_record
     *
     * @mbggenerated Mon Mar 28 10:41:33 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}