package com.qtt.sms.model;

import java.util.Date;

public class Template {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.agent_id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_type
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private Integer templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.signature
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.content
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.sender_mailbox
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String senderMailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.sender_nickname
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String senderNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.audit_status
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private Integer auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.enable_status
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private Integer enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.create_time
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.title
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.email_content
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    private String emailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.id
     *
     * @param id the value for template.id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.agent_id
     *
     * @return the value of template.agent_id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.agent_id
     *
     * @param agentId the value for template.agent_id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_id
     *
     * @return the value of template.template_id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_id
     *
     * @param templateId the value for template.template_id
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_type
     *
     * @return the value of template.template_type
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public Integer getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_type
     *
     * @param templateType the value for template.template_type
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setTemplateType(Integer templateType) {
        this.templateType = templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.signature
     *
     * @return the value of template.signature
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.signature
     *
     * @param signature the value for template.signature
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.content
     *
     * @return the value of template.content
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.content
     *
     * @param content the value for template.content
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.sender_mailbox
     *
     * @return the value of template.sender_mailbox
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getSenderMailbox() {
        return senderMailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.sender_mailbox
     *
     * @param senderMailbox the value for template.sender_mailbox
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setSenderMailbox(String senderMailbox) {
        this.senderMailbox = senderMailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.sender_nickname
     *
     * @return the value of template.sender_nickname
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getSenderNickname() {
        return senderNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.sender_nickname
     *
     * @param senderNickname the value for template.sender_nickname
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setSenderNickname(String senderNickname) {
        this.senderNickname = senderNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.audit_status
     *
     * @return the value of template.audit_status
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.audit_status
     *
     * @param auditStatus the value for template.audit_status
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.enable_status
     *
     * @return the value of template.enable_status
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public Integer getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.enable_status
     *
     * @param enableStatus the value for template.enable_status
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setEnableStatus(Integer enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.create_time
     *
     * @return the value of template.create_time
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.create_time
     *
     * @param createTime the value for template.create_time
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.title
     *
     * @return the value of template.title
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.title
     *
     * @param title the value for template.title
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.email_content
     *
     * @return the value of template.email_content
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public String getEmailContent() {
        return emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.email_content
     *
     * @param emailContent the value for template.email_content
     *
     * @mbggenerated Tue Mar 22 15:08:04 CST 2016
     */
    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }
    
    public String getTypeDesc() {
        String desc = "";
        switch (templateType) {
        case 0: desc = "短信"; break;
        case 1: desc = "邮件短信"; break;
        default: desc = "非法"; break;
        }
        return desc;
    }
    
    public String getAuditDesc() {
        String desc = "";
        switch (auditStatus) {
        case 0: desc = "待审核"; break;
        case 1: desc = "审核通过"; break;
        case 2: desc = "审核不通过"; break;
        case 3: desc = "139邮箱别名待验证"; break;
        default: desc = "非法"; break;
        }
        return desc;    	
    }
    
    public String getEnableDesc() {
        String desc = "";
        switch (enableStatus) {
        case 0: desc = "启用"; break;
        case 1: desc = "关闭"; break;
        default: desc = "非法"; break;
        }
        return desc;     	
    }
    //audit_status int(4) default 0 comment '审核状态。0：待审核 1：审核通过2：审核不通过 3：139邮箱别名待验证',
	//enable_status int(4) default 0 comment '启用状态。0：启用  1：关闭',
}