package com.qtt.sms.model;

import java.util.Date;

public class UserSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.session_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private String sessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_session.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.session_id
     *
     * @return the value of user_session.session_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.session_id
     *
     * @param sessionId the value for user_session.session_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.user_id
     *
     * @return the value of user_session.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.user_id
     *
     * @param userId the value for user_session.user_id
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_session.create_at
     *
     * @return the value of user_session.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_session.create_at
     *
     * @param createAt the value for user_session.create_at
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}