package com.qtt.sms.mapper;

import com.qtt.sms.model.AgentSession;
import com.qtt.sms.model.AgentSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int countByExample(AgentSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int deleteByExample(AgentSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int insert(AgentSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int insertSelective(AgentSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    List<AgentSession> selectByExample(AgentSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    AgentSession selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgentSession record, @Param("example") AgentSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByExample(@Param("record") AgentSession record, @Param("example") AgentSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByPrimaryKeySelective(AgentSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_session
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByPrimaryKey(AgentSession record);
}