package com.qtt.sms.mapper;

import com.qtt.sms.model.AgentLog;
import com.qtt.sms.model.AgentLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int countByExample(AgentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int deleteByExample(AgentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int insert(AgentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int insertSelective(AgentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    List<AgentLog> selectByExample(AgentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    AgentLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") AgentLog record, @Param("example") AgentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByExample(@Param("record") AgentLog record, @Param("example") AgentLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByPrimaryKeySelective(AgentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByPrimaryKey(AgentLog record);
}