package com.qtt.sms.mapper;

import com.qtt.sms.model.FailRecord;
import com.qtt.sms.model.FailRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FailRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int countByExample(FailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int deleteByExample(FailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int insert(FailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int insertSelective(FailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    List<FailRecord> selectByExample(FailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    FailRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") FailRecord record, @Param("example") FailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int updateByExample(@Param("record") FailRecord record, @Param("example") FailRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int updateByPrimaryKeySelective(FailRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fail_record
     *
     * @mbggenerated Mon Mar 28 10:47:10 CST 2016
     */
    int updateByPrimaryKey(FailRecord record);
}