package com.qtt.sms.mapper;

import com.qtt.sms.model.Passageway;
import com.qtt.sms.model.PassagewayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PassagewayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int countByExample(PassagewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int deleteByExample(PassagewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int insert(Passageway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int insertSelective(Passageway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    List<Passageway> selectByExample(PassagewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    Passageway selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") Passageway record, @Param("example") PassagewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int updateByExample(@Param("record") Passageway record, @Param("example") PassagewayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int updateByPrimaryKeySelective(Passageway record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passageway
     *
     * @mbggenerated Sat Jan 09 10:23:36 CST 2016
     */
    int updateByPrimaryKey(Passageway record);
}