package com.qtt.sms.mapper;

import com.qtt.sms.model.RechargeLog;
import com.qtt.sms.model.RechargeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int countByExample(RechargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int deleteByExample(RechargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int insert(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int insertSelective(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    List<RechargeLog> selectByExample(RechargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    RechargeLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") RechargeLog record, @Param("example") RechargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByExample(@Param("record") RechargeLog record, @Param("example") RechargeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByPrimaryKeySelective(RechargeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_log
     *
     * @mbggenerated Mon Dec 28 12:35:31 CST 2015
     */
    int updateByPrimaryKey(RechargeLog record);
}